import { useState } from 'react';
import { FaCreditCard, FaRocket, FaFileInvoiceDollar, FaRegCalendarAlt, FaHistory, FaCheck, FaExclamationTriangle, FaTimes, FaSpinner } from 'react-icons/fa';
import { useAuth } from '../context/AuthContext';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { subscriptionService, settingsService } from '../api/services';
import clsx from 'clsx';
import { Button } from '../components/ui/button';
import { format } from 'date-fns';
import { de } from 'date-fns/locale';

const PLANS = {
    basic: {
        name: 'Standard',
        price: '49,00 €',
        features: ['Bis zu 50 Projekte', '3 Team-Mitglieder', 'Standard Support', 'Basisfunktionen'],
        color: 'bg-slate-700',
        limit_projects: 50,
        limit_users: 3
    },
    pro: {
        name: 'Professional',
        price: '99,00 €',
        features: ['Unbegrenzte Projekte', '10 Team-Mitglieder', 'Priority Support', 'Erweiterte Berichte', 'API Zugriff'],
        color: 'bg-brand-primary',
        limit_projects: Infinity,
        limit_users: 10
    },
    premium: {
        name: 'Premium',
        price: '199,00 €',
        features: ['Unbegrenzte Projekte', '25 Team-Mitglieder', '24/7 Support', 'Custom Branding', 'Audit Logs', 'Dedicated Account Manager'],
        color: 'bg-purple-600',
        limit_projects: Infinity,
        limit_users: 25
    },
    enterprise: {
        name: 'Enterprise',
        price: 'Custom',
        features: ['Alles unbegrenzt', 'Unbegrenzte User', 'SLA', 'On-Premise Option', 'White Label'],
        color: 'bg-brand-primary',
        limit_projects: Infinity,
        limit_users: Infinity
    }
};

const Billing = () => {
    const { user, refreshUser } = useAuth();
    const queryClient = useQueryClient();
    const [showPlanModal, setShowPlanModal] = useState(false);
    const [showPaymentModal, setShowPaymentModal] = useState(false);

    // Fetch Invoices
    const { data: invoices, isLoading: isLoadingInvoices } = useQuery({
        queryKey: ['invoices'],
        queryFn: subscriptionService.getInvoices,
        initialData: []
    });

    // Fetch Company Settings (for Payment Method)
    const { data: companySettings } = useQuery({
        queryKey: ['companySettings'],
        queryFn: settingsService.getCompany
    });

    // Update Plan Mutation
    const updatePlanMutation = useMutation({
        mutationFn: subscriptionService.updatePlan,
        onSuccess: async () => {
            await refreshUser(); // Refresh user to get new plan in context
            queryClient.invalidateQueries({ queryKey: ['invoices'] }); // Invoices might change (autogenerated)
            setShowPlanModal(false);
            alert('Plan erfolgreich aktualisiert!');
        },
        onError: () => alert('Fehler beim Aktualisieren des Plans.')
    });

    // Update Payment Mutation
    const updatePaymentMutation = useMutation({
        mutationFn: subscriptionService.updatePaymentMethod,
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['companySettings'] });
            setShowPaymentModal(false);
            alert('Zahlungsmethode erfolgreich aktualisiert!');
        },
        onError: () => alert('Fehler beim Aktualisieren der Zahlungsmethode.')
    });

    if (!user || !user.tenant) {
        return <div className="p-10 text-center">Laden...</div>;
    }

    const currentPlanId = (user.tenant.subscription_plan || 'basic') as keyof typeof PLANS;
    const activePlan = PLANS[currentPlanId] || PLANS.basic;

    const nextBillingDate = new Date(); // In real app, fetch from subscription start/end
    nextBillingDate.setMonth(nextBillingDate.getMonth() + 1);
    nextBillingDate.setDate(1);

    const handleUpdatePlan = (planId: string) => {
        updatePlanMutation.mutate(planId);
    };

    const handleUpdatePayment = (e: React.FormEvent) => {
        e.preventDefault();
        const formData = new FormData(e.target as HTMLFormElement);
        updatePaymentMutation.mutate({
            card_holder: formData.get('card_holder'),
            card_number: formData.get('card_number'),
            card_expiry: formData.get('card_expiry'),
        });
    };

    const downloadInvoice = (url: string | null) => {
        if (!url) {
            alert('PDF Generierung ist aktulll deaktiviert (Demo).');
            return;
        }
        window.open(url, '_blank');
    };

    const paymentMethod = companySettings?.card_last_four ? {
        last4: companySettings.card_last_four,
        brand: companySettings.card_brand || 'VCard',
        expiry: companySettings.card_expiry || '12/99'
    } : null;

    return (
        <div className="max-w-5xl mx-auto fade-in h-screen overflow-y-auto pb-20 custom-scrollbar">
            {/* Header */}
            <div className="mb-8">
                <h1 className="text-2xl font-medium text-slate-800">Abonnement & Abrechnung</h1>
                <p className="text-slate-500 text-sm">Verwalten Sie Ihren Plan, Zahlungsmethoden und laden Sie Belege herunter.</p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Main Content */}
                <div className="lg:col-span-2 space-y-8">
                    {/* Active Plan */}
                    <div className="bg-white rounded-sm shadow-sm border border-slate-200 overflow-hidden relative">
                        <div className="absolute top-4 right-4">
                            <span className={clsx("px-2 py-1 text-xs font-medium rounded border",
                                user.tenant.status === 'active' ? "bg-emerald-50 text-emerald-700 border-emerald-100" : "bg-red-50 text-red-700 border-red-100"
                            )}>
                                {user.tenant.status === 'active' ? 'Aktiv' : 'Inaktiv'}
                            </span>
                        </div>
                        <div className="p-6">
                            <div className="flex items-center gap-4 mb-6">
                                <div className={clsx("w-12 h-12 rounded text-white flex items-center justify-center text-xl shadow-sm", activePlan.color)}>
                                    <FaRocket />
                                </div>
                                <div>
                                    <h3 className="text-xl font-medium text-slate-800">{activePlan.name}</h3>
                                    <p className="text-slate-500 text-xs font-medium">Ihr aktueller Plan</p>
                                </div>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                                {activePlan.features.map((feature, i) => (
                                    <div key={i} className="flex items-center gap-3 text-sm text-slate-600">
                                        <div className="w-5 h-5 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center text-xs"><FaCheck /></div>
                                        <span className="font-medium">{feature}</span>
                                    </div>
                                ))}
                            </div>

                            <div className="flex flex-col sm:flex-row items-center gap-3 pt-6 border-t border-slate-100">
                                <Button className="w-full sm:w-auto bg-brand-primary text-white hover:bg-brand-primary/90 transition-all shadow-sm font-bold">
                                    Plan verwalten
                                </Button>
                                <button
                                    onClick={() => setShowPlanModal(true)}
                                    className="w-full sm:w-auto px-4 py-2 bg-white border border-slate-300 text-slate-700 rounded text-sm font-medium hover:bg-slate-50 transition-all"
                                >
                                    Paket wechseln
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* Payment Method */}
                    <div className="bg-white rounded-sm shadow-sm border border-slate-200 overflow-hidden">
                        <div className="p-4 border-b border-slate-100 bg-transparent flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <div className="w-7 h-7 rounded bg-white border border-slate-200 text-slate-500 flex items-center justify-center text-xs shadow-sm">
                                    <FaCreditCard />
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-slate-800">Zahlungsmethode</h3>
                                </div>
                            </div>
                            <button onClick={() => setShowPaymentModal(true)} className="text-xs font-medium text-slate-900 hover:text-slate-800 bg-slate-50 px-2 py-1 rounded border border-slate-100 transition-colors">Bearbeiten</button>
                        </div>
                        <div className="p-5">
                            {paymentMethod ? (
                                <div className="flex items-center justify-between p-3 bg-white rounded border border-slate-200 shadow-sm hover:border-slate-200 transition-colors cursor-pointer group">
                                    <div className="flex items-center gap-3">
                                        <div className="w-10 h-6 bg-[#1A1F71] rounded flex items-center justify-center text-white font-medium text-xs italic shadow-sm">
                                            {paymentMethod.brand}
                                        </div>
                                        <div>
                                            <p className="text-xs font-medium text-slate-800 group-hover:text-slate-900 transition-colors">•••• {paymentMethod.last4}</p>
                                            <p className="text-xs text-slate-400 font-medium">Läuft ab: {paymentMethod.expiry}</p>
                                        </div>
                                    </div>
                                    <span className="px-1.5 py-0.5 bg-slate-100 text-slate-500 text-xs font-medium rounded border border-slate-200">Standard</span>
                                </div>
                            ) : (
                                <div className="text-center p-4 border border-dashed border-slate-200 rounded text-xs text-slate-400">
                                    Keine Zahlungsmethode hinterlegt
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Billing History */}
                    <div className="bg-white rounded-sm shadow-sm border border-slate-200 overflow-hidden">
                        <div className="p-4 border-b border-slate-100 bg-transparent flex items-center gap-2">
                            <div className="w-7 h-7 rounded bg-white border border-slate-200 text-slate-500 flex items-center justify-center text-xs shadow-sm">
                                <FaHistory />
                            </div>
                            <h3 className="text-sm font-medium text-slate-800">Rechnungshistorie</h3>
                        </div>
                        <div className="overflow-x-auto">
                            <table className="w-full text-left">
                                <thead>
                                    <tr className="bg-transparent text-xs font-medium text-slate-400 border-b border-slate-100">
                                        <th className="px-6 py-4">Datum</th>
                                        <th className="px-6 py-4">Beleg-Nr.</th>
                                        <th className="px-6 py-4 text-right">Betrag</th>
                                        <th className="px-6 py-4 text-center">Status</th>
                                        <th className="px-6 py-4"></th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-50">
                                    {invoices?.length > 0 ? (
                                        invoices.map((inv: any, i: number) => (
                                            <tr key={i} className="hover:bg-slate-50 transition-colors group">
                                                <td className="px-6 py-4 text-xs text-slate-500 font-medium">{format(new Date(inv.invoice_date), 'dd. MMM yyyy', { locale: de })}</td>
                                                <td className="px-6 py-4 text-xs font-medium text-slate-800 group-hover:text-slate-900 transition-colors">{inv.invoice_number}</td>
                                                <td className="px-6 py-4 text-xs font-medium text-slate-800 text-right">{new Intl.NumberFormat('de-DE', { style: 'currency', currency: inv.currency }).format(Number(inv.amount))}</td>
                                                <td className="px-6 py-4 text-center">
                                                    <span className={clsx("px-1.5 py-0.5 text-xs font-medium rounded border flex items-center justify-center gap-1 w-fit mx-auto",
                                                        inv.status === 'paid' ? "bg-emerald-50 text-emerald-700 border-emerald-100" : "bg-slate-50 text-slate-900 border-slate-100"
                                                    )}>
                                                        {inv.status === 'paid' && <FaCheck className="text-xs" />} {inv.status}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-4 text-right">
                                                    <button onClick={() => downloadInvoice(inv.pdf_url)} className="p-2 text-slate-300 hover:text-slate-900 hover:bg-slate-50 rounded transition-all" title="PDF Herunterladen">
                                                        <FaFileInvoiceDollar />
                                                    </button>
                                                </td>
                                            </tr>
                                        ))
                                    ) : (
                                        <tr>
                                            <td colSpan={5} className="px-6 py-8 text-center text-xs text-slate-400 italic">
                                                {isLoadingInvoices ? "Lade Rechnungen..." : "Keine Rechnungen vorhanden"}
                                            </td>
                                        </tr>
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {/* Sidebar Info */}
                <div className="space-y-6">
                    <div className="bg-slate-900 rounded-sm p-5 text-white shadow-sm relative overflow-hidden ring-1 ring-white/10">
                        <div className="relative z-10">
                            <h3 className="text-xs font-medium opacity-60 mb-6 flex items-center gap-2">
                                <FaRegCalendarAlt /> Nächste Abrechnung
                            </h3>
                            <div className="flex flex-col gap-1 mb-8">
                                <p className="text-3xl font-medium tracking-tight">01. {nextBillingDate.toLocaleString('default', { month: 'long' })}</p>
                                <p className="text-white/50 text-sm font-medium">Voraussichtlich {activePlan.price}</p>
                            </div>

                            <div className="space-y-4">
                                <div className="p-3 bg-white/5 rounded border border-white/5 backdrop-blur-sm">
                                    <div className="flex justify-between text-xs font-medium mb-2 text-white/70">
                                        <span>Projekte</span>
                                        <span>{activePlan.limit_projects === Infinity ? '∞' : activePlan.limit_projects} / Monat</span>
                                    </div>
                                    <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
                                        <div className="h-full bg-emerald-500 w-[15%] transition-all duration-1000"></div>
                                    </div>
                                    <p className="text-xs text-white/40 mt-2 text-right">3 Projekte diesen Monat</p>
                                </div>
                                <div className="p-3 bg-white/5 rounded border border-white/5 backdrop-blur-sm">
                                    <div className="flex justify-between text-xs font-medium mb-2 text-white/70">
                                        <span>Team</span>
                                        <span>{activePlan.limit_users === Infinity ? '∞' : activePlan.limit_users} User</span>
                                    </div>
                                    <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
                                        <div className="h-full bg-blue-500 w-[40%] transition-all duration-1000"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* Subtle decorative element */}
                        <div className="absolute top-0 right-0 -mr-16 -mt-16 w-64 h-64 bg-slate-700/20 rounded-full blur-[80px]"></div>
                        <div className="absolute bottom-0 left-0 -ml-16 -mb-16 w-48 h-48 bg-purple-500/10 rounded-full blur-[60px]"></div>
                    </div>

                    <div className="bg-white rounded-sm p-5 border border-slate-200 shadow-sm">
                        <h4 className="text-xs font-medium text-slate-800 mb-3 flex items-center gap-2">
                            Hilfe & Support
                        </h4>
                        <p className="text-xs text-slate-500 mb-5 leading-relaxed">
                            Fragen zu Ihrer Rechnung oder Ihrem Abonnement? Unser Support hilft Ihnen gerne weiter oder passen Sie Ihren Plan an.
                        </p>
                        <button className="w-full py-2 bg-slate-50 border border-slate-200 text-slate-700 rounded text-xs font-medium hover:bg-slate-100 hover:border-slate-300 transition-all">
                            Support kontaktieren
                        </button>
                    </div>

                    {user.tenant.status !== 'active' && (
                        <div className="bg-red-50 rounded-sm p-6 border border-red-100">
                            <h4 className="text-xs font-medium text-red-800 mb-2 flex items-center gap-2">
                                <FaExclamationTriangle /> Account Status
                            </h4>
                            <p className="text-xs text-red-700 leading-relaxed mb-3">
                                Ihr Account ist derzeit inaktiv oder gesperrt. Bitte kontaktieren Sie den Support.
                            </p>
                        </div>
                    )}
                </div>
            </div>
            {/* Plan Modal */}
            {showPlanModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-fadeIn">
                    <div className="bg-white rounded-sm shadow-sm w-full max-w-4xl max-h-[90vh] overflow-y-auto">
                        <div className="p-6 border-b border-slate-100 flex justify-between items-center sticky top-0 bg-white z-10">
                            <h2 className="text-xl font-medium text-slate-800">Plan wählen</h2>
                            <button onClick={() => setShowPlanModal(false)} className="text-slate-400 hover:text-red-500 transition-colors"><FaTimes /></button>
                        </div>
                        <div className="p-8 grid grid-cols-1 md:grid-cols-3 gap-6">
                            {Object.entries(PLANS).filter(([key]) => key !== 'enterprise').map(([key, plan]) => (
                                <div key={key} className={clsx("border-2 rounded-sm p-6 relative transition-all duration-300 hover:shadow-sm cursor-pointer",
                                    currentPlanId === key ? "border-brand-primary bg-slate-50 ring-1 ring-brand-primary" : "border-slate-100 hover:border-slate-200"
                                )}>
                                    {currentPlanId === key && <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-brand-primary text-white text-xs font-bold px-3 py-1 rounded-full">Aktuell</div>}
                                    <h3 className="text-lg font-medium text-slate-800 mb-2">{plan.name}</h3>
                                    <div className="text-3xl font-semibold text-slate-900 mb-4">{plan.price}<span className="text-sm font-medium text-slate-400">/mtl.</span></div>
                                    <ul className="space-y-3 mb-8">
                                        {plan.features.slice(0, 4).map((f, i) => (
                                            <li key={i} className="flex items-start gap-2 text-xs text-slate-600">
                                                <FaCheck className="text-emerald-500 mt-0.5 shrink-0" />
                                                <span className="leading-tight">{f}</span>
                                            </li>
                                        ))}
                                    </ul>
                                    <Button
                                        onClick={() => handleUpdatePlan(key)}
                                        disabled={currentPlanId === key || updatePlanMutation.isPending}
                                        className={clsx(
                                            "w-full font-bold",
                                            currentPlanId === key
                                                ? "bg-slate-200 text-slate-400 cursor-not-allowed"
                                                : "bg-brand-primary text-white hover:bg-brand-primary/90 shadow-sm"
                                        )}
                                    >
                                        {updatePlanMutation.isPending && currentPlanId !== key ? <FaSpinner className="animate-spin mx-auto" /> : (currentPlanId === key ? "Aktiv" : "Wählen")}
                                    </Button>
                                </div>
                            ))}
                        </div>
                        <div className="p-6 bg-slate-50 border-t border-slate-100 text-center">
                            <p className="text-sm text-slate-500">Für Enterprise Lösungen kontaktieren Sie bitte unseren <a href="#" className="text-slate-900 font-medium hover:underline">Vertrieb</a>.</p>
                        </div>
                    </div>
                </div>
            )}

            {/* Payment Modal */}
            {showPaymentModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-fadeIn">
                    <div className="bg-white rounded-sm shadow-sm w-full max-w-md">
                        <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                            <h2 className="text-lg font-medium text-slate-800">Zahlungsmethode</h2>
                            <button onClick={() => setShowPaymentModal(false)} className="text-slate-400 hover:text-red-500 transition-colors"><FaTimes /></button>
                        </div>
                        <form onSubmit={handleUpdatePayment} className="p-6 space-y-4">
                            <div>
                                <label className="block text-xs font-medium text-slate-500 mb-1.5">Karteninhaber</label>
                                <input name="card_holder" type="text" className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-sm text-sm outline-none focus:border-slate-900 transition-colors" placeholder="Max Mustermann" required />
                            </div>
                            <div>
                                <label className="block text-xs font-medium text-slate-500 mb-1.5">Kartennummer</label>
                                <div className="relative">
                                    <input name="card_number" type="text" className="w-full px-4 py-2 pl-10 bg-slate-50 border border-slate-200 rounded-sm text-sm outline-none focus:border-slate-900 transition-colors font-brand" placeholder="0000 0000 0000 0000" maxLength={16} required />
                                    <FaCreditCard className="absolute left-3 top-2.5 text-slate-400" />
                                </div>
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-medium text-slate-500 mb-1.5">Gültig bis</label>
                                    <input name="card_expiry" type="text" className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-sm text-sm outline-none focus:border-slate-900 transition-colors text-center" placeholder="MM/JJ" required />
                                </div>
                                <div>
                                    <label className="block text-xs font-medium text-slate-500 mb-1.5">CVC</label>
                                    <input name="card_cvc" type="text" className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-sm text-sm outline-none focus:border-slate-900 transition-colors text-center" placeholder="123" required />
                                </div>
                            </div>
                            <div className="pt-4">
                                <Button
                                    type="submit"
                                    disabled={updatePaymentMutation.isPending}
                                    className="w-full py-6 bg-brand-primary text-white hover:bg-brand-primary/90 transition-all flex justify-center items-center gap-2 font-bold shadow-lg shadow-brand-primary/20"
                                >
                                    {updatePaymentMutation.isPending ? <><FaSpinner className="animate-spin" /> Speichern...</> : "Karte speichern"}
                                </Button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Billing;
